#85 Override executed script
4sh/datamaintain pull request #119
Opened 2021-02-09 11:02 UTC by driccio

Override executed script 

Resolves/Fixes/Closes #85

2021-02-10 21:01 UTC, Lysoun requested changes
Since this can't be in a review comment, I'm telling here: the action of ```DatamaintainConfig``` should be added in the ```log``` function of the class.

I don't see anything regarding the new option for the configuration to enable Datamaintain to choose to override executed scripts, is that normal?

2021-02-16 10:19 UTC, driccio commented on modules/core/src/main/kotlin/datamaintain/core/script/Script.kt
>                  )
I agree with you. But I will not manage that in my PR.

2021-02-16 10:22 UTC, driccio commented on modules/core/src/main/kotlin/datamaintain/core/step/executor/Executor.kt
> +                else -> simulateAction(script)
You're absolutely right.

2021-02-16 10:56 UTC, driccio commented on modules/core/src/main/kotlin/datamaintain/core/script/FileScript.kt
> +        override var action: ScriptAction = ScriptAction.RUN
I agree with you but it extends ScriptWithContent that needs this information.

2021-02-23 08:38 UTC, nroulon approved these changes

2021-02-23 08:39 UTC, Lysoun commented on modules/cli/src/main/kotlin/datamaintain/cli/App.kt
> +
An issue was created to deal with that: #121 
I am resolving the conversation

2021-02-23 09:01 UTC, merged